# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c7b7497b3d527be3d556ca43c15c4f637cebcd6eb9df8e9e0fd165784c1218a446148edf33436c62ec794817089da5fea36e7ab23c9adac39a19bd667a77f60b

test:
  secret_key_base: a37f931581a64ca79f3c727f96eb74aee0dd95f3e6967fd9d6294776f41595fc1720e3ca47f2fbb80b96e9aeb2f2ef0b14dc730063834e94d4d790767359f4b4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
